### ISSUE TITLE
Incorporating New Data

### ISSUE THREAD

**Issue by lmilord** [RobertCorey/bps-assets#14]
Entries that La'Kendra, the intern, has compiled can be found in Google sheets in this Google Drive folder:

https://drive.google.com/drive/folders/0BxhKlO-OhafTeTE2bEduUlZRUUE?usp=sharing

Can these be added?

(will there be a mass upload feature in the future, or will it be manual entries? She's working more on Tuesday, 6/27 to add more entries)

**Comment by RobertCorey** [comment]
will add current data.
